-- Migration: Create residential_buildings_unit_types table for API #7
CREATE TABLE IF NOT EXISTS public.residential_buildings_unit_types (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pnu VARCHAR(19) NOT NULL,
    exclusive_area NUMERIC(10, 2) NOT NULL,
    pyung_type INTEGER,
    household_count INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_unit_types_pnu ON public.residential_buildings_unit_types (pnu);
CREATE INDEX IF NOT EXISTS idx_unit_types_area ON public.residential_buildings_unit_types (exclusive_area);

-- Grant privileges for Supabase roles
GRANT ALL ON TABLE public.residential_buildings_unit_types TO anon, authenticated, service_role;
